---
- name: "8、修改{{soft_name}}配置文件"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: 'setid.sh.j2', dest: '{{ install_path }}/{{ soft_name }}/bin/setid.sh' }
    - { src: 'zkServer.sh.j2', dest: '{{ install_path }}/{{ soft_name }}/bin/zkServer.sh' }
    - { src: 'zoo.cfg.j2', dest: '{{ install_path }}/{{ soft_name }}/conf/zoo.cfg' }

- name: "9、写入myid"
  shell: "source {{ install_path }}/{{ soft_name }}/bin/setid.sh"

- name: "10、目录赋权"
  command: chown -R {{ user }}:{{ group }} {{ install_path }}

- name: "11、启动{{soft_name}}集群"
  command: su - {{ user }} -c "{{ install_path }}/{{ soft_name }}/bin/zkServer.sh start"

- name: "12、hold on"
  command: sleep 120

- name: "13、删除临时文件"
  file:
    path: '/tmp/apache-zookeeper-3.6.1-bin.tar.gz'
    state: absent

- name: "14、获取{{soft_name}}集群状态"
  command: "{{ install_path }}/{{ soft_name }}/bin/zkServer.sh status"
  register: status

- name: "15、打印{{soft_name}}集群状态"
  debug: var=status.stdout_lines
