---
- name: "1、拷贝安装包"
  copy:
    src: "apache-tomcat-8.5.64.tar.gz"
    dest: "/tmp/"

- name: "2、解压源码包"
  unarchive:
    src: "/tmp/apache-tomcat-8.5.64.tar.gz"
    dest: "{{ install_path }}"
    remote_src: yes

- name: "3、建立软链接"
  file:
    src: "{{ install_path }}/apache-tomcat-8.5.64"
    dest: "{{ install_path }}/tomcat8"
    state: link

- name: "4、启动tomcat"
  shell: nohup {{ install_path }}/tomcat8/bin/startup.sh 

- name: "5、删除临时文件"
  file:
    path: '/tmp/apache-tomcat-8.5.64.tar.gz'
    state: absent
